### PR TITLE
Command Suggestion "Sudo"

### PR DESCRIPTION
**Pull request by landenjw**
Adds the functionality to remotely execute commands as other players in the server. Useful for debug purposes, etc.

I've actually been using this for awhile now in my projects and think it would be useful for some developers using nexus admin, and even for non-developers.

### CODE REVIEW

**Comment by TheNexusAvenger** [comment]
The implementation is fine and appears to prevent privilege escalation. I'm concerned about log forging though. Forcibly performing a command as someone can be used maliciously to frame another admin for running commands they aren't meant to run. For example, while in `logs` the `sudo` command log will appear before (hopefully that is seen), `featureflaglogs` would not. A theoretical custom ban system with logging wouldn't either.

**Comment by ezekieltem** [comment]
A possible solution for the issue mentioned with sudo regarding `logs` and `featureflaglogs`.
The third argument of `Executor:ExecuteCommandWithOrWithoutPrefix()` which is for CommandData could be passed where the name of the user running `:sudo` is under the key `Sudo`.

In [ServerRegistry.lua](https://github.com/TheNexusAvenger/Nexus-Admin/blob/master/src/Server/ServerRegistry.lua), where logs are added into the `MainLogs` (line 55), fetch the CommandData from the CommandContext, and if the key `Sudo` has a value modify the message added to `MainLogs`.

For `featureflag` add a new key into the table saved to the *FeatureFlagLogsDataStore* with the value stored under `Sudo` in the CommandData, then account for the **possible** new key when displaying the logs.

*I am unsure of how to use the "request changes" feature or any other feature to suggest changed to files in pull request, here is the code I wrote for the above*

### sudo.lua
*Differences are located at the `Executor:ExecuteCommandWithOrWithoutPrefix()`*
```lua
--[[
TheNexusAvenger
Implementation of a command.
--]]
--!strict

local IncludedCommandUtil = require(script.Parent.Parent:WaitForChild("IncludedCommandUtil"))
local Types = require(script.Parent.Parent.Parent:WaitForChild("Types"))

local Players = game:GetService("Players")

return {
    Keyword = {"sudo"},
    Category = "UsefulFunCommands",
    Description = "Force a player to run a command.",
    Arguments = {
        {
            Type = "nexusAdminPlayers",
            Name = "Players",
            Description = "Players to sudo",
        },
        {
            Type = "string",
            Name = "Command",
            Description = "Command to use",
        },
    },
    ClientLoad = function(Api : Types.NexusAdminApiClient)
        local SudoRemote = (IncludedCommandUtil:GetRemote("SudoRemote") :: RemoteEvent)

        local Player = Players.LocalPlayer

        SudoRemote.OnClientEvent:Connect(function(Command, SudoExecutorName)
            local Executor = Players:FindFirstChild(SudoExecutorName)
            if not Executor then return end
            local LocalPlayerLevel = Api.Authorization:YieldForAdminLevel(Player)
            local ExecutorLevel = Api.Authorization:YieldForAdminLevel(Executor)

            if ExecutorLevel < LocalPlayerLevel and Executor ~= Player then return end
            Api.Executor:ExecuteCommandWithOrWithoutPrefix(Command,Player,{Sudo=SudoExecutorName})
        end)
    end,
    ServerLoad = function(Api : Types.NexusAdminApiServer)
        local SudoRemote = (IncludedCommandUtil:CreateRemote("RemoteEvent","SudoRemote") :: RemoteEvent)
    end,
    ServerRun = function(CommandContext: Types.CmdrCommandContext, Players : {Player}, Command : string)
        local Util = IncludedCommandUtil.ForContext(CommandContext)
        local Api = Util:GetApi() :: Types.NexusAdminApiServer

        local SudoRemote = (Util:GetRemote("SudoRemote") :: RemoteEvent)

        local ExecutorLevel = Api.Authorization:YieldForAdminLevel(CommandContext.Executor)

        local PlayersSudoed = 0

        for _, Player in pairs(Players) do
            local PlayerLevel = Api.Authorization:YieldForAdminLevel(Player)
            if ExecutorLevel >= PlayerLevel or Player == CommandContext.Executor then
                SudoRemote:FireClient(Player,Command,CommandContext.Executor.Name)
                PlayersSudoed += 1
            end
        end

        return "Sudo'ed "..tostring(PlayersSudoed).."/"..tostring(#Players).." players."
    end
}
```

### ServerRegistry.lua
*Differences are located in the `task.spawn()` within the `BeforeRun` hook register*
```lua
--[[
TheNexusAvenger

Registers commands on the server.
--]]
--!strict

local Registry = require(script.Parent.Parent:WaitForChild("Common"):WaitForChild("Registry"))
local Types = require(script.Parent.Parent:WaitForChild("Types"))

local ServerRegistry = {}
ServerRegistry.__index = ServerRegistry
setmetatable(ServerRegistry, Registry)



--[[
Creates the server registry.
--]]
function ServerRegistry.new(Cmdr: Types.Cmdr, Configuration: Types.Configuration, Authorization: Types.Authorization, Messages: Types.MessagesServer, Logs: Types.Logs, Time: Types.Time, Filter: Types.FilterServer, NexusAdminRemotes: Folder): Types.RegistryServer
    local self = Registry.new(Authorization, Configuration, Messages, Cmdr, NexusAdminRemotes) :: any
    setmetatable(self, ServerRegistry)
    self.ClientData = {}

    --Create the remote objects.
    local RegistryEvents = Instance.new("Folder")
    RegistryEvents.Name = "RegistryEvents"
    RegistryEvents.Parent = NexusAdminRemotes

    local GetRegisteredCommands = Instance.new("RemoteFunction")
    GetRegisteredCommands.Name = "GetRegisteredCommands"
    GetRegisteredCommands.Parent = RegistryEvents
    self.GetRegisteredCommands = GetRegisteredCommands

    local CommandRegistered = Instance.new("RemoteEvent")
    CommandRegistered.Name = "CommandRegistered"
    CommandRegistered.Parent = RegistryEvents
    self.CommandRegistered = CommandRegistered

    --Connect the remote objects.
    function GetRegisteredCommands.OnServerInvoke()
        return self.ClientData
    end

    --Register the BeforeRun hook for verifying admin levels and logging.
    self.Cmdr.Registry:RegisterHook("BeforeRun", function(CommandContext: Types.CmdrCommandContext): ()
        --Return if a result exists from the common function.
        local BeforeRunResult = self:PerformBeforeRun(CommandContext)
        if BeforeRunResult then
            return BeforeRunResult
        end

        --Log the command asynchronously.
        task.spawn(function()
            local CommandData = (CommandContext:GetData() :: {Sudo: string?, [any]: any}) or {Sudo = nil}
            local LogMessage = CommandContext.Executor.Name.." ["..Time:GetTimeString().."]: "..Filter:FilterString(CommandContext.RawText,CommandContext.Executor)
            if CommandData.Sudo then
                LogMessage = CommandData.Sudo.." sudo'ed - "..LogMessage
            end
            Logs:Add(LogMessage)
        end)
        return nil
    end)

    --Return the object.
    return (self :: any) :: Types.RegistryServer
end

--[[
Loads a command.
--]]
function ServerRegistry:LoadCommand(CommandData: Types.NexusAdminCommandData): ()
    Registry.LoadCommand(self :: any, CommandData)

    --Add and send the command data.
    table.insert(self.ClientData, CommandData)
    self.CommandRegistered:FireAllClients(CommandData)

    --Register the command.
    local CmdrCommandData = self:GetReplicatableCmdrData(CommandData) :: Types.NexusAdminCommandData
    CmdrCommandData.Run = self:CreateRunMethod(CommandData)
    self.Cmdr.Registry:RegisterCommandObject(CmdrCommandData)

    --Load the command.
    if (CommandData :: any).OnCommandLoad then
        warn("OnCommandLoad (used in "..CmdrCommandData.Name..") is deprecated as of V.2.0.0. All commands are loaded as of V.2.0.0, so this is no longer needed.");
        (CommandData :: any).OnCommandLoad()
    end
end



return (ServerRegistry :: any) :: Types.RegistryServer
```

### featureflag.lua
*Differences are in the `table.insert` within `ServerRun`*
```lua
--[[
TheNexusAvenger

Implementation of a command.
--]]
--!strict

local IncludedCommandUtil = require(script.Parent.Parent:WaitForChild("IncludedCommandUtil"))
local Types = require(script.Parent.Parent.Parent:WaitForChild("Types"))

return {
    Keyword = {"featureflag", "feature"},
    Category = "Administrative",
    Description = "Sets the value of a feature flag.",
    Arguments = {
        {
            Type = "nexusAdminFastFlags",
            Name = "Feature",
            Description = "Feature flags to change.",
        },
        {
            Type = "boolean",
            Name = "Value",
            Description = "New value of the feature flag.",
        },
    },
    ServerRun = function(CommandContext: Types.CmdrCommandContext, FeatureFlags: {string}, Value: boolean)
        local Util = IncludedCommandUtil.ForContext(CommandContext)
        local Api = Util:GetApi()
        
        --Log the feature flag change.
        if Api.CommandData.FeatureFlagLogsDataStore then
            local PreviousValues = {}
            for _, FeatureFlag in FeatureFlags do
                PreviousValues[FeatureFlag] = Api.FeatureFlags:GetFeatureFlag(FeatureFlag)
            end
            task.spawn(function()
                Api.CommandData.FeatureFlagLogsDataStore:Update("FeatureFlagChangesLog", function(OldLogs)
                    OldLogs = OldLogs or {}
                    for _, FeatureFlag in FeatureFlags do
                        table.insert(OldLogs, {
                            Time = os.time(),
                            UserId = CommandContext.Executor.UserId,
                            UserName = CommandContext.Executor.Name,
                            Name = FeatureFlag,
                            PreviousValue = PreviousValues[FeatureFlag],
                            NewValue = Value,
                            Sudo = (CommandContext:GetData() :: {Sudo:string?, [any]:any} or {Sudo=nil}).Sudo
                        })
                    end
                    return OldLogs
                end)
            end)
        end

        --Change the feature flags.
        for _, FeatureFlag in FeatureFlags do
            Api.FeatureFlags:SetFeatureFlag(FeatureFlag, Value)
        end
    end,
}
```

### featureflaglogs.lua
*Differences are in the `GetFeatureFlagLogsFunction.OnServerInvoke()` starting from `local Line`*
```lua
--[[
TheNexusAvenger

Implementation of a command.
--]]
--!strict

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local IncludedCommandUtil = require(script.Parent.Parent:WaitForChild("IncludedCommandUtil"))
local Types = require(script.Parent.Parent.Parent:WaitForChild("Types"))

return {
    Keyword = "featureflaglogs",
    Category = "Administrative",
    Description = "Opens up a window logs of feature flag changes.",
    ServerLoad = function(Api: Types.NexusAdminApiServer)
        local NexusDataStore = require(ReplicatedStorage:WaitForChild("NexusAdminClient"):WaitForChild("NexusFeatureFlags"):WaitForChild("NexusDataStore")) :: any
        xpcall(function()
            Api.CommandData.FeatureFlagLogsDataStore = NexusDataStore:GetDataStore("NexusAdmin_Persistence", "FeatureFlagLogs")
        end, function(ErrorMessage)
            warn("Failed to get feature flag logs because "..tostring(ErrorMessage))
        end)

        local GetFeatureFlagLogsFunction = Instance.new("RemoteFunction")
        GetFeatureFlagLogsFunction.Name = "GetFeatureFlagLogs"
        GetFeatureFlagLogsFunction.Parent = Api.EventContainer
    
        function GetFeatureFlagLogsFunction.OnServerInvoke(Player): {string}
            if Api.Authorization:IsPlayerAuthorized(Player, Api.Configuration:GetCommandAdminLevel("Administrative", "featureflaglogs")) then
                if Api.CommandData.FeatureFlagLogsDataStore then
                    local LogEntries = Api.CommandData.FeatureFlagLogsDataStore:Get("FeatureFlagChangesLog") or {}
                    local Logs = {}
                    for i = #LogEntries, 1, -1 do
                        local Log = LogEntries[i]
                        local Line
                        if Log.Sudo then
                            Line = Api.Time:GetDateTimeString(Log.Time)..": "..Log.Sudo.." sudo'ed - "..Log.UserName.." changed "..Log.Name.." from "..tostring(Log.PreviousValue).." to "..tostring(Log.NewValue)
                        else
                            Line = Api.Time:GetDateTimeString(Log.Time)..": "..Log.UserName.." changed "..Log.Name.." from "..tostring(Log.PreviousValue).." to "..tostring(Log.NewValue)
                        end
                        table.insert(Logs, Line)
                    end
                    return Logs
                else
                    return {"Logs failed to load."}
                end
            else
                return {"Unauthorized"}
            end
        end
    end,
    ClientRun = function(CommandContext: Types.CmdrCommandContext)
        local Util = IncludedCommandUtil.ForContext(CommandContext)
        local Api = Util:GetApi()
        local ScrollingTextWindow = require(Util.ClientResources:WaitForChild("ScrollingTextWindow")) :: any

        --Display the text window.
        local FeatureFlagLogs = nil
        local Window = ScrollingTextWindow.new()
        Window.Title = "Feature Flag Logs"
        Window.GetTextLines = function(_, SearchTerm, ForceRefresh)
            --Get the logs.
            if not FeatureFlagLogs or ForceRefresh then
                FeatureFlagLogs = (Api.EventContainer:WaitForChild("GetFeatureFlagLogs") :: RemoteFunction):InvokeServer()
            end

            --Filter and return the feature flags logs.
            local FilteredLogs = {}
            for _, Message in FeatureFlagLogs do
                if string.find(string.lower(Message), string.lower(SearchTerm)) then
                    table.insert(FilteredLogs, Message)
                end
            end
            return FilteredLogs
        end
        Window:Show()
    end,
}
```

**Comment by landenjw** [comment]
@ezekieltem 
I really like the way you went about doing this. I was actually thinking of handing this a very similar way. Thank you for your contribution!

**Comment by TheNexusAvenger** [comment]
I'm still too nervous about this command to make it part of Nexus Admin for everyone. While you addressed the log forging issues I mentioned with the included commands, this does not help existing commands implemented for individual games (like Innovation Security's). I also realized that this could be used for commands like `h`, `m`, `pm`, `ph`, and `pchat` to maliciously force admins to say things *to users who can't see logs*.

An alternative I will suggest is to make this command a `ModuleScript` that can simply be parented to the Nexus Admin loader, and then upload that module to the toolbox.

**Pull request closed without merging**
