### PR TITLE
changeing keybind for cmd bar

### PR DESCRIPTION
**Pull request by Chrisrankingservices**

### CODE REVIEW

**Review by TheNexusAvenger — CHANGES_REQUESTED** [review]
This change changes the key for toggling the command bar for everyone with no way to configure it to use the previous behavior. If anything, it should be changed to a configuration option with the default being the legacy option of backslash.

**Comment by Chrisrankingservices** [comment]
ok, let me find out how to do it

**Comment by Chrisrankingservices** [comment]
did I do it?

**Review by Chrisrankingservices — COMMENTED** [review]
fixing

**Comment by Chrisrankingservices** [comment]
pending review.

**Comment by TheNexusAvenger** [comment]
It doesn't seem like anything has changed. Did you push your changes?

**Comment by Chrisrankingservices** [comment]
check now

**Comment by TheNexusAvenger** [comment]
That change doesn't resolve the problem that this changes the behavior for everyone and can't be configured. It is changing the hard-coded value from one to another. Nothing has changed with this and there is no point to merging it as it causes an error due to using `Backslash` instead of `BackSlash`.

**Comment by Chrisrankingservices** [comment]
check now

**Comment by TheNexusAvenger** [comment]
The pull request now has no changes except for adding a new line to the file. There is no point to merging it and it doesn't resolve the original issue.

**Comment by Chrisrankingservices** [comment]
ok.. i changeed the BackSlash thing, i'm lost at this point so should i just delete this..

**Pull request closed without merging**
