### PR TITLE
Add cmdr commandbar featureflag

### PR DESCRIPTION
**Pull request by Thodor12**
Added the ability to toggle the usage of the Cmdr command bar with the usage of a new feature flag.

### CODE REVIEW

**Comment by TheNexusAvenger** [comment]
What is the use case of this? Is there a reason you don't want to have the command bar usable?

**Comment by Thodor12** [comment]
I personally do not like the style of the command bar and rather not have visible. Instead just using the chat and/or possibly a custom command bar gui.
Additionally for the audience that is going to be using my game I think the command bar is going to be too complex, they won't understand it properly, so I rather just want to prevent them from using it and becoming confused.

**Comment by TheNexusAvenger** [comment]
This functionality actually does exist. For use with Innovation Security, the admin level required to use `cmdbar` is set to 0 instead of -1, which also makes it so the command bar is not togglable for non-admins (see: https://github.com/TheNexusAvenger/Nexus-Admin/blob/master/src/IncludedCommands/Local/Administrative/cmdbar.lua#L42). Setting the required admin level above in the loader to something above owner admin should work with this. I don't like the idea of having 2 conditions to have the command bar enabled.

**Comment by Thodor12** [comment]
I see, I hadn't considered that yet. I'll just set it to 0 to get the same effect.

**Pull request closed without merging**
